### ISSUE TITLE
gsheets error: Unknown pattern "d/m/yyyy".

### ISSUE THREAD

**Issue by harishanumula** [betodealmeida/shillelagh#95]
It is getting parsed properly in the google sheets, even showing a calendar dropdown in sheets, but getting this error when importing in superset. @betodealmeida

**Comment by betodealmeida** [comment]
Thanks, @harishanumula! I'll do a quick fix to include the pattern. I'm currently working on a branch (https://github.com/betodealmeida/shillelagh/tree/icu) that will handle any pattern, but it's going to take some time.

**Comment by harishanumula** [comment]
Thanks @betodealmeida, please add all the date formats possible with date. like (mm/dd/yyyy), (dd/mm/yy), (dd/mm/yyyy)

**Comment by RhysDavis** [comment]
+1 to this!

**Comment by jesse042811** [comment]
Hey @betodealmeida - I am facing a similar issue with my dashboard. 

Unknown pattern "yyyy-mm-dd".

**Comment by betodealmeida** [comment]
Thanks @jesse042811 — working on it right now, I should have a fix in the next few days.

**Comment by samlopezic** [comment]
Hi @betodealmeida thanks for looking into this.  Adding my error.

Unknown pattern "dd-mm-yyyy"

Working on a Google Sheet with dates formated for Chile.

**Comment by jesse042811** [comment]
Any update on this bug? @betodealmeida

**Comment by betodealmeida** [comment]
@jesse042811 not yet, working on it tonight.

Can you share a spreadsheet where the problem happens so I can test?

**Comment by jesse042811** [comment]
I am thinking you mean screenshot and I will provide more information later
tonight.

**Comment by betodealmeida** [comment]
@jesse042811 no, I really meant spreadsheet — a link to a spreadsheet where the date is formatted as "yyyy-mm-dd", so I can test the solution. It can have just 1 column and bogus data. I'll also create one to test, but I might overlook something, so if someone has a link that I can test it would be better.

**Comment by samlopezic** [comment]
Hi @betodealmeida , here is a spreeadsheet with pattern "dd-mm-yyyy"

https://docs.google.com/spreadsheets/d/1yL0dMFQpQTxXXMWEOcj8GRc90NBUz4aKVOfeMUCk2SM/edit?usp=sharing

Thanks

**Comment by betodealmeida** [comment]
@harishanumula @RhysDavis @jesse042811 @samlopezic I just released 1.0.4, with a full parser/formatter that should support any patterns. I tested with the patterns that you provided and also with the sheet that @samlopezic linked, and everything worked successfully.

Sorry for the delay, but I wanted to write a robust solution that should handle custom formats, not just the most popular ones. Let me know if you have any other problems!

**Comment by jesse042811** [comment]
@betodealmeida 
Still not working for me, here is a spreadsheet from a project with a similar format. https://docs.google.com/spreadsheets/d/1Azlmysl62rK6a3fW2Tc287Egxoo3QvIMKhJ-u8eAMjc/edit#gid=0

**Comment by betodealmeida** [comment]
@jesse042811 can you share the spreadsheet with roberto@dealmeida.net? I'll take a look.

**Comment by betodealmeida** [comment]
Closing since I talked with @jesse042811 and the problem they're seeing is with an older version.
